infraOperator:
  config:
    chartComponent:
      git: https://github.com/th2-net/infra-operator-tpl.git
      ref: release-v0.4.0
      path: ./component/
    chartDictionary:
      git: https://github.com/th2-net/infra-operator-tpl.git
      ref: release-v0.4.0
      path: ./dictionary/

infraMgr:
  git:
    repository: git@github.com:th2-net/th2-infra-demo-configuration.git

rabbitmq:
  prometheus:
    operator:
      enabled: false
  persistentVolume:
    enabled: true
    storageClass: local-storage
    size: 10Gi

cassandra:
  internal: false
  host: <cassandra-host>
