apiVersion: v1
data:
  log4j.properties: |
    log4j.rootLogger=INFO, CON

    log4j.appender.CON=org.apache.log4j.ConsoleAppender
    log4j.appender.CON.layout=org.apache.log4j.PatternLayout
    log4j.appender.CON.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss,SSS} %-6p [%-15t] %c - %m%n

    log4j.logger.com.exactpro.th2=DEBUG
    log4j.logger.com.exactpro.evolution=DEBUG
    log4j.logger.com.exactpro.cradle=DEBUG

    log4j.logger.com.exactpro.sf.services.http=DEBUG
  
  log4py.conf: |
    [loggers]
    keys=root

    [handlers]
    keys=consoleHandler

    [formatters]
    keys=formatter

    [logger_root]
    level=DEBUG
    handlers=consoleHandler

    [handler_consoleHandler]
    class=StreamHandler
    level=DEBUG
    formatter=formatter
    args=(sys.stdout,)

    [handler_fileHandler]
    class=FileHandler
    level=DEBUG
    formatter=formatter
    args=('../all.log',)

    [formatter_formatter]
    format=%(asctime)s %(levelname)s %(message)s

  log4cxx.properties: |
    log4cxx::helpers::Properties properties;
    properties.setProperty(L"log4j.rootLogger",L"DEBUG");
    properties.setProperty(L"log4j.appender",L"ca");
    properties.setProperty(L"log4j.appender",L"fa");

  logLevel:
    INFO

kind: ConfigMap
metadata:
  name: logging-config
