apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2dictionaries.th2.exactpro.com
spec:
  group: th2.exactpro.com
  names:
    kind: Th2Dictionary
    listKind: Th2DictionaryList
    plural: th2dictionaries
    singular: th2dictionary
  scope: Namespaced
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      description: Th2Dictionary defines th2 dictionary instance
      properties:
        apiVersion:
          description: ''
          type: string
        kind:
          description: ''
          type: string
        metadata:
          type: object
        spec:
          description: Specification of desired dictionary
          type: object
          properties:
            data:
              type: string
          required:
            - data
      required:
        - spec
      type: object
  version: v1
  versions:
    - name: v1
      served: true
      storage: true

   # subresources describes the subresources for custom resources.
  subresources:
     # status enables the status subresource.
    status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
