apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: th2links.th2.exactpro.com
spec:
  conversion:
    strategy: None
  group: th2.exactpro.com
  names:
    kind: Th2Link
    listKind: Th2LinkList
    plural: th2links
    singular: th2link
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Th2link defines th2 link instance
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Specification of desired links
            properties:
              boxes-relation:
                properties:
                  router-grpc:
                    description: List of grpc connection pins
                    items:
                      properties:
                        from:
                          properties:
                            box:
                              type: string
                            pin:
                              type: string
                            service-class:
                              type: string
                            strategy:
                              type: string
                          required:
                          - strategy
                          - box
                          - pin
                          type: object
                        name:
                          type: string
                        to:
                          properties:
                            box:
                              type: string
                            pin:
                              type: string
                            service-class:
                              type: string
                            strategy:
                              type: string
                          required:
                          - strategy
                          - box
                          - pin
                          type: object
                      required:
                      - name
                      - from
                      - to
                      type: object
                    type: array
                  router-mq:
                    description: List of mq connection pins
                    items:
                      properties:
                        from:
                          properties:
                            box:
                              type: string
                            pin:
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                        name:
                          type: string
                        to:
                          properties:
                            box:
                              type: string
                            pin:
                              type: string
                          required:
                          - box
                          - pin
                          type: object
                      required:
                      - name
                      - from
                      - to
                      type: object
                    type: array
                type: object
              dictionaries-relation:
                description: List of dictionary relations
                items:
                  properties:
                    box:
                      type: string
                    dictionary:
                      properties:
                        name:
                          type: string
                        type:
                          enum:
                          - MAIN
                          - LEVEL1
                          - LEVEL2
                          - INCOMING
                          - OUTGOING
                          type: string
                      required:
                      - name
                      type: object
                    name:
                      type: string
                  required:
                  - name
                  - box
                  - dictionary
                  type: object
                type: array
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: Th2Link
    listKind: Th2LinkList
    plural: th2links
    singular: th2link
  conditions:
  - lastTransitionTime: "2020-09-29T16:05:12Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2020-09-29T16:05:12Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
